### ISSUE TITLE
ffmpeg break

### ISSUE THREAD

**Issue by tym3515** [MuxLabs/ws-ingest#5]
FFmpeg STDERR: [flv @ 000001fc12158500] Failed to update header with correct duration.
[flv @ 000001fc12158500] Failed to update header with correct filesize.
Error writing trailer of rtmp://

**Comment by mmcc** [comment]
This can happen for a few reasons, but the most common in my experience has been when the browser isn't able to broadcast chunks fast enough. Some browsers essentially de-prioritize JS execution if the tab isn't focused, which can cause this, but I've also seen it happen when the client's upload bandwidth is constrained.

Going to close this because there's just not enough information to go on here, but if you can reply with some more details please do!
